os:
  - linux
  - osx

language: go
sudo: false

go:
  - tip
  - 1.8
  - 1.7
install:
  - make devdeps
script:
  - make analyze
  - make cover
after_success:
  - bash <(curl -s https://codecov.io/bash)
notifications:
  email:
    - tiago.katcipis@neoway.com.br
    - matheus.vill@neoway.com.br
    - kamila.hinckel@neoway.com.br
